# config/packages/security.yaml

security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      entry_point: App\Security\UserAuthenticator
      form_login:
        login_path: login
        check_path: login
      logout:
        path: logout
        target: /
      custom_authenticator: App\Security\UserAuthenticator

      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /
        # by default, the feature is enabled by checking a checkbox in the
        # login form, uncomment the following line to always enable it.
        #always_remember_me: true

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
